language: node_js
node_js:
  - '6'
addons:
  code_climate:
    repo_token: 8e506e5386e606830c503b5827c0e1c086c2b4c2bd0d3f4bcbcb19bfe20b8803
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
after_success:
  - npm run coverage
  - 'npm run mocha:json'
  - 'bash <(curl -s https://codecov.io/bash)'
  - 'bash <(curl -s https://codecov.octoblu.com/bash)'
branches:
  only:
    - '/^v[0-9]/'
notifications:
  webhooks:
    - 'https://beekeeper.octoblu.com/webhooks/travis:ci'
